name: test-build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/bake-action@v6
